import streamlit as st
import os
from crew_agents import run_multiagent_personality_pipeline
from dotenv import load_dotenv

load_dotenv()

st.set_page_config(
    page_title="Personality Mirror — MultiAgent (CrewAI)",
    layout="centered"
)

# ---------------------------------------------------------
# Sidebar Footer Styling
# ---------------------------------------------------------
st.markdown("""
<style>
    /* Make sidebar layout flexible so footer stays at bottom */
    [data-testid="stSidebar"] > div:first-child {
        display: flex;
        flex-direction: column;
        height: 100%;
    }
    .sidebar-footer {
        margin-top: auto;
        padding: 10px 5px;
        text-align: center;
        font-size: 14px;
        color: #444;
        opacity: 0.8;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# Sidebar content
# ---------------------------------------------------------
st.sidebar.image("https://em-content.zobj.net/source/microsoft-teams/363/mirror_1fa9e.png", width=80)
st.sidebar.title("Personality Mirror")
st.sidebar.markdown("""
Welcome! This app uses multiple AI agents to analyze your personality based on your answers.  
Fill out the form and get your personalized report!
""")
st.sidebar.info("Your data is private and never stored.")

# ---- Footer in Sidebar ----
st.sidebar.markdown("<div class='sidebar-footer'>Made by <b>Harshad Chavan</b></div>", unsafe_allow_html=True)

# ---------------------------------------------------------
# Soft styling for main content
# ---------------------------------------------------------
st.markdown("""
    <style>
        .stApp {
            background: linear-gradient(120deg, #ffe4f0 0%, #fff6fa 100%);
        }
        .trait-card {
            background: #fff6fa;
            border-radius: 10px;
            box-shadow: 0 1px 6px #f8bbd0;
            padding: 1em;
            margin-bottom: 1em;
            border-left: 4px solid #ffb6d5;
            color: #222;
        }
        h4, .stSubheader, .stTitle, .stTextInput label, .stButton>button {
            color: #222 !important;
        }
        .stButton>button {
            background-color: #ffb6d5;
            color: #222;
            border-radius: 8px;
            font-size: 16px;
            padding: 0.5em 1.5em;
        }
        .stTextInput>div>input {
            background: #fff6fa;
            border-radius: 6px;
            color: #222;
        }
        .stExpander, .stInfo, .stSuccess, .stError {
            background: #fff6fa !important;
            color: #222 !important;
        }
    </style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.markdown("<h1 style='font-size:2.5em; color:#222;'>🪞 Personality Mirror Agent</h1>", unsafe_allow_html=True)
st.write("<span style='font-size:18px; color:#222;'>Answer 5 short questions and get a personality mirror generated by multiple AI agents.</span>", unsafe_allow_html=True)

# ---------------------------------------------------------
# Input Form
# ---------------------------------------------------------
with st.form("personality_form"):
    col1, col2 = st.columns(2)

    with col1:
        name = st.text_input("Your name (optional)")
        q1 = st.text_input("1) What do you enjoy doing in your free time?")
        q2 = st.text_input("2) How would your friends describe you in 3 words?")

    with col2:
        q3 = st.text_input("3) What stresses you out the most?")
        q4 = st.text_input("4) Describe a recent decision you made and why.")
        q5 = st.text_input("5) What is a personal strength and a weakness?")

    submitted = st.form_submit_button("Generate Personality Mirror")

# ---------------------------------------------------------
# Run Pipeline
# ---------------------------------------------------------
if submitted:
    answers = [q1.strip(), q2.strip(), q3.strip(), q4.strip(), q5.strip()]

    if not any(answers):
        st.error("Please answer at least one question.")
    else:
        with st.spinner("Running multi-agent analysis..."):
            try:
                result = run_multiagent_personality_pipeline(answers, name=name)
                st.success("Personality mirror generated successfully!")

                # Summary
                st.markdown("<h2 style='color:#222;'>Summary</h2>", unsafe_allow_html=True)
                st.markdown(f"<div style='color:#222;font-size:1.1em;'>{result.get('summary', '—')}</div>", unsafe_allow_html=True)

                # Traits
                st.markdown("<h2 style='color:#222;'>Traits</h2>", unsafe_allow_html=True)
                traits = result.get("traits", {})
                if traits:
                    for trait, score in traits.items():
                        st.markdown(f"<div class='trait-card'><b>{trait}</b><br>Score: {score}</div>", unsafe_allow_html=True)

                # Recommendations
                st.markdown("<h2 style='color:#222;'>Recommendations</h2>", unsafe_allow_html=True)
                for r in result.get("recommendations", []):
                    st.markdown(f"<span style='color:#222;'>- {r}</span>", unsafe_allow_html=True)

                # Validation message
                st.markdown("<h2 style='color:#222;'>Validation</h2>", unsafe_allow_html=True)
                st.markdown(f"<span style='color:#222;'>{result.get('validating_message', '')}</span>", unsafe_allow_html=True)

                # Download button
                st.download_button(
                    label="Download Report",
                    data=str(result),
                    file_name="personality_mirror_report.txt",
                    mime="text/plain"
                )

                # Debug
                with st.expander("Debug / Raw Output"):
                    st.json(result.get("raw", {}))

            except Exception as e:
                st.error(f"Error generating personality mirror: {e}")
